name: Deploy Hexo to GitHub Pages

concurrency:
  group: hexo-deploy
  cancel-in-progress: false

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
  schedule:
    # - cron: '0 20 * * *'   # UTC 20:00 = 北京时间 04:00
    - cron: '0 12 * * *' 
    #        * * * * *
    #        │ │ │ │ │
    #        │ │ │ │ └─── 星期几 (0-7, 0和7都代表周日)
    #        │ │ │ └───── 月份 (1-12)
    #        │ │ └─────── 日期 (1-31)
    #        │ └───────── 小时 (0-23)
    #        └─────────── 分钟 (0-59)
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # 当前仓库只需读取
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HEXO }}
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Install Hexo Git Deployer
        run: |
          npm install hexo-deployer-git --save
          npm install hexo-cli -g

      - name: Restore daily recommend cache
        uses: actions/cache@v4
        with:
          path: source/_data/daily-recommend.json
          key: daily-recommend-${{ github.run_id }}
          restore-keys: |
            daily-recommend-

      - name: Clean and Generate Static Files
        run: |
          hexo clean
          hexo generate

      - name: Configure Git
        run: |
          git config --global init.defaultBranch main
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.HEXO }}    # 使用 PAT，不是 GITHUB_TOKEN
          external_repository: ranecoco/ranecoco.github.io # 目标仓库
          # github_token: ${{ secrets.HEXO }}
          publish_dir: ./public
          publish_branch: master

      # - name: Commit updated recommend data
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add source/_data/daily-recommend.json
      #     git diff --staged --quiet || git commit -m "chore: update daily recommend data [skip ci]"
      #     git push
